<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <BaseOutputPath>C:\Program Files\Epic Games\MountAndBlade2\Modules\TimeMaster\bin\</BaseOutputPath>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Settings\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\Modules\Bannerlord.Harmony\bin\Win64_Shipping_Client\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="SandBox">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.DotNet.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.Engine.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>..\..\..\..\..\Program Files\Epic Games\MountAndBlade2\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
